default: &default
  adapter: postgresql
  host: db
  username: postgres
  encoding: unicode
  port: 5432
  pool: 5

development:
  <<: *default
  database: vendas_development

test:
  <<: *default
  database: vendas_test

production:
  <<: *default
  database: vendas_production
  username: vendas
  password: <%= ENV['VENDAS_DATABASE_PASSWORD'] %>
