# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 431ccc6e5d2af19c77f3a1abb2a4f76855a7fc19f7bdf2a90dc52e6a64818e9859d32b7a3ca661be29e7b46c615b98108b5cd3e13903a0e7fc933b1c156ef673

test:
  secret_key_base: 84fa6ad095bc000e14622c67697b0e5943f483b6b80d6888313bef8ff1445d86d11ca5647a079f5339427524698f33c27171f2a1f11485042ea028fd9cc9604e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
